### ISSUE TITLE
Amazing Project !

### ISSUE THREAD

**Issue by esakarya** [myrrkel/odoo-openai#3]
Thanks for this amazing project !
May ask you can ai bot integrate with odoo ? 
for eg: what my order status ? i saw some field can connect odoo tables.

**Comment by myrrkel** [comment]
Thank you for your feedback!
Open AI tools are made for this kind of features. (https://platform.openai.com/docs/guides/function-calling)
To use tools with the Odoo AI bot, go on the AI bot Completion and add a new tool (take example on search_question_answer that allows the bot to find answers in a knowledge database)

![image](https://github.com/myrrkel/odoo-openai/assets/13931670/37e6f6b8-5d69-4ec3-bb8a-03135ae02824)

Create you own function (e.g: get_orders_status) in a custom module, set the model where the function is, add the parameters with their type, and explain to the bot how to you use it. That's it ;)
![image](https://github.com/myrrkel/odoo-openai/assets/13931670/8c4c2d37-76b1-41ad-b2e1-1280e9db324e)

**Comment by esakarya** [comment]
It looks complicated. If there was a demo similar to this, I could understand the logic more easily :) I will try it, thank you very much.
